<?php

declare(strict_types=1);

namespace SugarCraft\Crush\Tests\Skills;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use SugarCraft\Crush\Skills\Skill;
use SugarCraft\Crush\Skills\SkillRegistry;

/**
 * E85 — what a `paths:` frontmatter glob actually claims.
 *
 * {@see SkillRegistry::pathMatches()} replaced three hand-rolled
 * `str_replace()` rewrites of `**` with a real pattern-to-PCRE translation.
 * The rewrites were each keyed on a SLASH BEFORE the stars, so a pattern
 * STARTING with `**` matched none of them and fell through to a bare
 * `fnmatch()` that reads `**\/` as "some characters, then a literal slash" —
 * which is why `**\/*.php` did not claim `a.php`.
 *
 * THE POINT OF THIS FILE IS THE TABLE, not the named cases. A translation that
 * silently stops matching something the rewrites matched is a regression that
 * no individual example would catch, so the OLD predicate's full answer over
 * 42 patterns x 50 paths was captured BEFORE the change and is carried forward
 * here verbatim as {@see BEFORE}. {@see AFTER} is the same grid under the
 * translation. The suite asserts three things about them: AFTER is what the
 * shipped code returns, AFTER is a strict SUPERSET of BEFORE, and the
 * difference is exactly the leading-`**` set — so a future edit that widens
 * the matcher somewhere else has to say so here.
 *
 * MEASURED on PHP 8.3.6 (this box has only 8.3; CI also runs 8.4). Everything
 * the table encodes is `fnmatch()`/PCRE behaviour, both of which are stable
 * across those two, but the version is on the record because `fnmatch()` is a
 * libc passthrough and the grid is a stdlib-behaviour claim.
 */
#[CoversClass(SkillRegistry::class)]
final class SkillPathPatternTest extends TestCase
{
    /**
     * Column order for {@see BEFORE} and {@see AFTER}.
     *
     * @var list<string>
     */
    private const PATHS = [
            'a.php', 'a.md', 'src/a.php', 'src/deep/a.php', 'src/x/y/a.php', 'src', 'src/', 'a', 'a/b', 'a/x/b',
            'ab', 'a/xb', 'a.php/b.php', 'docs/a.md', 'docs/x/a.md', 'tests/x/yTest.php', '/abs/x/a.php',
            '/abs/a.php', 'a/b/c', 'abc', 'a/c', 'abd', 'a*b', 'aXb', 'src/x/z/y/q/a.go', 'node_modules/x/y.js',
            'p/node_modules/y.js', '', 'x_test.php', 'q/x_test.php', 'a[b', 'a]b', 'a.b+c(d).php', 'x.php',
            'q/x.php', 'src/a', 'src/a/b', 'a/b/c/d', 'x/', 'x/y/', '.hidden/z.py', '.hidden/q/z.py', 'a{b,c}.php',
            'ab.php', 'a|b.php', 'a$b^c.php', 'ünï/f.php', 'ünï/q/f.php', '**/*.php', 'a/b/**',
    ];

    /**
     * Row order for {@see BEFORE} and {@see AFTER}.
     *
     * @var list<string>
     */
    private const PATTERNS = [
            '*.php', '*.md', 'src/*.php', 'src/**/*.php', '**/*.php', '**/*_test.php', 'src/**', '**', '**/',
            'docs/**/*.md', 'a/**/b', 'a/**b', 'a**b', '**.php', 'src/**/**/*.php', 'tests/**/*Test.php',
            '/abs/**/*.php', 'a/b/**', 'a?c', 'a[bc]d', 'a\\*b', 'src/*', 'src/**/x/**/*.go', '**/node_modules/**',
            'a[b', 'a]b', 'a[!x]b', 'a[]]b', 'a.b+c(d).php', 'a\\[b', '***/*.php', 'src/***', 'a/**/**/b', '*/**',
            '**/*', 'x/**/', '.hidden/**/*.py', 'a{b,c}.php', 'a|b.php', 'a$b^c.php', 'ünï/**/*.php', '**/x/**',
    ];

    /**
     * The predicate this change REPLACED, frozen.
     *
     * Generated by running the pre-change body of `getForPaths()` — bare
     * `fnmatch($pattern, $path)`, then, when the pattern contained `**`, the
     * three rewrites `/**\/`->`/*\/`, `/**`->`/*` and `/**`->`''` ORed
     * together — over {@see PATTERNS} x {@see PATHS} at 8416d98e on PHP 8.3.6.
     * 290 of the 2,100 pairs matched.
     *
     * @var array<string, string>
     */
    private const BEFORE = [
            '*.php'              => '10111000000010011100000000001100111000000011111110',
            '*.md'               => '01000000000001100000000000000000000000000000000000',
            'src/*.php'          => '00111000000000000000000000000000000000000000000000',
            'src/**/*.php'       => '00111000000000000000000000000000000000000000000000',
            '**/*.php'           => '00111000000010011100000000000100001000000000001110',
            '**/*_test.php'      => '00000000000000000000000000000100000000000000000000',
            'src/**'             => '00111110000000000000000010000000000110000000000000',
            '**'                 => '11111111111111111111111111111111111111111111111111',
            '**/'                => '00000010000000000000000000000000000000110000000000',
            'docs/**/*.md'       => '00000000000001100000000000000000000000000000000000',
            'a/**/b'             => '00000000110000000000000000000000000000000000000000',
            'a/**b'              => '00000000111100000000000000000000000000000000000000',
            'a**b'               => '00000000111100000000001100000011000000000000000000',
            '**.php'             => '10111000000010011100000000001100111000000011111110',
            'src/**/**/*.php'    => '00111000000000000000000000000000000000000000000000',
            'tests/**/*Test.php' => '00000000000000010000000000000000000000000000000000',
            '/abs/**/*.php'      => '00000000000000001100000000000000000000000000000000',
            'a/b/**'             => '00000000100000000010000000000000000001000000000001',
            'a?c'                => '00000000000000000001100000000000000000000000000000',
            'a[bc]d'             => '00000000000000000000010000000000000000000000000000',
            'a\\*b'              => '00000000000000000000001000000000000000000000000000',
            'src/*'              => '00111010000000000000000010000000000110000000000000',
            'src/**/x/**/*.go'   => '00000000000000000000000010000000000000000000000000',
            '**/node_modules/**' => '00000000000000000000000000100000000000000000000000',
            'a[b'                => '00000000000000000000000000000010000000000000000000',
            'a]b'                => '00000000000000000000000000000001000000000000000000',
            'a[!x]b'             => '00000000100000000000001100000011000000000000000000',
            'a[]]b'              => '00000000000000000000000000000001000000000000000000',
            'a.b+c(d).php'       => '00000000000000000000000000000000100000000000000000',
            'a\\[b'              => '00000000000000000000000000000010000000000000000000',
            '***/*.php'          => '00111000000010011100000000000100001000000000001110',
            'src/***'            => '00111110000000000000000010000000000110000000000000',
            'a/**/**/b'          => '00000000100000000000000000000000000000000000000000',
            '*/**'               => '11111111111111111111111111111111111111111111111111',
            '**/*'               => '00111010110111111110100011100100001111111100001111',
            'x/**/'              => '00000000000000000000000000000000000000110000000000',
            '.hidden/**/*.py'    => '00000000000000000000000000000000000000001100000000',
            'a{b,c}.php'         => '00000000000000000000000000000000000000000010000000',
            'a|b.php'            => '00000000000000000000000000000000000000000000100000',
            'a$b^c.php'          => '00000000000000000000000000000000000000000000010000',
            'ünï/**/*.php'     => '00000000000000000000000000000000000000000000001100',
            '**/x/**'            => '00001000010000111000000011000000000000000000000000',
    ];

    /**
     * What the shipped translation returns over the same grid: 331 pairs.
     *
     * @var array<string, string>
     */
    private const AFTER = [
            '*.php'              => '10111000000010011100000000001100111000000011111110',
            '*.md'               => '01000000000001100000000000000000000000000000000000',
            'src/*.php'          => '00111000000000000000000000000000000000000000000000',
            'src/**/*.php'       => '00111000000000000000000000000000000000000000000000',
            '**/*.php'           => '10111000000010011100000000001100111000000011111110',
            '**/*_test.php'      => '00000000000000000000000000001100000000000000000000',
            'src/**'             => '00111110000000000000000010000000000110000000000000',
            '**'                 => '11111111111111111111111111111111111111111111111111',
            '**/'                => '00000010000000000000000000010000000000110000000000',
            'docs/**/*.md'       => '00000000000001100000000000000000000000000000000000',
            'a/**/b'             => '00000000110000000000000000000000000000000000000000',
            'a/**b'              => '00000000111100000000000000000000000000000000000000',
            'a**b'               => '00000000111100000000001100000011000000000000000000',
            '**.php'             => '10111000000010011100000000001100111000000011111110',
            'src/**/**/*.php'    => '00111000000000000000000000000000000000000000000000',
            'tests/**/*Test.php' => '00000000000000010000000000000000000000000000000000',
            '/abs/**/*.php'      => '00000000000000001100000000000000000000000000000000',
            'a/b/**'             => '00000000100000000010000000000000000001000000000001',
            'a?c'                => '00000000000000000001100000000000000000000000000000',
            'a[bc]d'             => '00000000000000000000010000000000000000000000000000',
            'a\\*b'              => '00000000000000000000001000000000000000000000000000',
            'src/*'              => '00111010000000000000000010000000000110000000000000',
            'src/**/x/**/*.go'   => '00000000000000000000000010000000000000000000000000',
            '**/node_modules/**' => '00000000000000000000000001100000000000000000000000',
            'a[b'                => '00000000000000000000000000000010000000000000000000',
            'a]b'                => '00000000000000000000000000000001000000000000000000',
            'a[!x]b'             => '00000000100000000000001100000011000000000000000000',
            'a[]]b'              => '00000000000000000000000000000001000000000000000000',
            'a.b+c(d).php'       => '00000000000000000000000000000000100000000000000000',
            'a\\[b'              => '00000000000000000000000000000010000000000000000000',
            '***/*.php'          => '10111000000010011100000000001100111000000011111110',
            'src/***'            => '00111110000000000000000010000000000110000000000000',
            'a/**/**/b'          => '00000000110000000000000000000000000000000000000000',
            '*/**'               => '11111111111111111111111111111111111111111111111111',
            '**/*'               => '11111111111111111111111111111111111111111111111111',
            'x/**/'              => '00000000000000000000000000000000000000110000000000',
            '.hidden/**/*.py'    => '00000000000000000000000000000000000000001100000000',
            'a{b,c}.php'         => '00000000000000000000000000000000000000000010000000',
            'a|b.php'            => '00000000000000000000000000000000000000000000100000',
            'a$b^c.php'          => '00000000000000000000000000000000000000000000010000',
            'ünï/**/*.php'     => '00000000000000000000000000000000000000000000001100',
            '**/x/**'            => '00001000010000111000000011000000000000110000000000',
    ];

    public function testTheShippedMatcherReturnsExactlyTheCharacterisedTable(): void
    {
        $actual = [];
        foreach (self::PATTERNS as $pattern) {
            $bits = '';
            foreach (self::PATHS as $path) {
                $bits .= SkillRegistry::pathMatches($pattern, $path) ? '1' : '0';
            }
            $actual[$pattern] = $bits;
        }

        self::assertSame(self::AFTER, $actual);
    }

    /**
     * The regression guard the brief asked for: no pair the three rewrites
     * matched may stop matching.
     *
     * Asserted SEPARATELY from the table above even though the table already
     * encodes it, because the two fail with different messages. A changed
     * table says "the grid moved"; this says WHICH pattern lost WHICH path,
     * which is the only thing a reader needs to decide whether the narrowing
     * was intended.
     */
    public function testTheTranslationNeverNarrowsWhatTheOldRewritesMatched(): void
    {
        $lost = [];
        foreach (self::PATTERNS as $pattern) {
            foreach (self::PATHS as $i => $path) {
                if (self::BEFORE[$pattern][$i] !== '1') {
                    continue;
                }
                if (!SkillRegistry::pathMatches($pattern, $path)) {
                    $lost[] = sprintf('%s <- %s', var_export($pattern, true), var_export($path, true));
                }
            }
        }

        self::assertSame([], $lost, 'the pattern translation stopped matching paths the old rewrites claimed');
    }

    /**
     * And the widening is exactly the two holes, not a blank cheque.
     *
     * Every pair the translation gains over the old predicate must be
     * attributable to a named defect in the rewrites. There are TWO, and the
     * second was found by this assertion rather than by the brief:
     *
     *  - LEADING GLOBSTAR. Each rewrite needed a slash in front of the stars,
     *    and at position 0 there is none, so `**\/*.php` never reached any of
     *    them.
     *  - ADJACENT GLOBSTARS. `str_replace('/**\/', '/*\/', 'a/**\/**\/b')`
     *    consumes the trailing slash of the first match, so the scan resumes
     *    PAST the slash the second `/**\/` needed and only the first is
     *    rewritten: the result is `a/*\/**\/b`, which claims `a/x/y/b` but not
     *    `a/x/b`. Non-overlapping replacement, not a missing case — which is
     *    why reading the three rewrites as a list of cases does not find it.
     *
     * A gain outside both means the translation changed a semantic nobody
     * decided to change.
     */
    public function testEveryPairTheTranslationGainsComesFromANamedHoleInTheRewrites(): void
    {
        $gained = [];
        foreach (self::PATTERNS as $pattern) {
            foreach (self::PATHS as $i => $path) {
                if (self::BEFORE[$pattern][$i] === '1' || !SkillRegistry::pathMatches($pattern, $path)) {
                    continue;
                }
                $gained[] = [$pattern, $path];
            }
        }

        self::assertNotSame([], $gained, 'nothing widened at all — E85 is not fixed');

        $holes = [];
        foreach ($gained as [$pattern, $path]) {
            $hole = match (true) {
                str_starts_with($pattern, '**')      => 'leading globstar',
                str_contains($pattern, '/**/**/')    => 'adjacent globstars',
                default                              => 'UNCLASSIFIED',
            };
            $holes[$hole] = true;

            self::assertNotSame(
                'UNCLASSIFIED',
                $hole,
                sprintf(
                    'pattern %s newly claims %s, and it belongs to neither named hole — the translation '
                    . 'widened something other than what E85 is about',
                    var_export($pattern, true),
                    var_export($path, true),
                ),
            );
        }

        // Both holes are still exercised by the grid; dropping the pattern that
        // covers one would otherwise leave this test green over half a fix.
        self::assertSame(
            ['adjacent globstars', 'leading globstar'],
            $this->sorted(array_keys($holes)),
        );
    }

    /**
     * @param list<string> $values
     * @return list<string>
     */
    private function sorted(array $values): array
    {
        sort($values);

        return $values;
    }

    /**
     * The headline case, stated once in the open so it survives a rewrite of
     * the table: the first form most people write.
     */
    public function testALeadingGlobstarClaimsFilesAtTheRootOfTheTree(): void
    {
        self::assertTrue(SkillRegistry::pathMatches('**/*.php', 'a.php'));
        self::assertTrue(SkillRegistry::pathMatches('**/*.php', 'src/a.php'));
        self::assertTrue(SkillRegistry::pathMatches('**/*.php', 'src/deep/a.php'));

        // MEASURED on PHP 8.3.6: this is what the bare fnmatch() the old code
        // fell through to answers for the first of the three, and it is the
        // whole defect.
        self::assertFalse(fnmatch('**/*.php', 'a.php'));
    }

    /**
     * `/**` still spans ZERO directories, which is what the third rewrite
     * bought and the easiest thing for a regex translation to lose.
     */
    public function testAnInteriorGlobstarStillSpansZeroDirectories(): void
    {
        self::assertTrue(SkillRegistry::pathMatches('src/**/*.php', 'src/a.php'));
        self::assertTrue(SkillRegistry::pathMatches('src/**/*.php', 'src/deep/a.php'));
        self::assertTrue(SkillRegistry::pathMatches('a/**', 'a'));
        self::assertTrue(SkillRegistry::pathMatches('a/**', 'a/b/c'));
    }

    /**
     * A single `*` still crosses `/`, because the call site never passed
     * `FNM_PATHNAME` and narrowing it would drop matches that hold today.
     *
     * VERIFIED on PHP 8.3.6, both branches, so the claim is not taken on
     * trust: without flags `fnmatch('*.php', 'src/a.php')` is true, with
     * `FNM_PATHNAME` it is false.
     */
    public function testASingleStarStillCrossesTheSeparator(): void
    {
        self::assertTrue(fnmatch('*.php', 'src/a.php'));
        self::assertFalse(fnmatch('*.php', 'src/a.php', FNM_PATHNAME));

        self::assertTrue(SkillRegistry::pathMatches('*.php', 'src/a.php'));
        self::assertTrue(SkillRegistry::pathMatches('src/*', 'src/x/y/a.php'));
        self::assertTrue(SkillRegistry::pathMatches('a?c', 'a/c'));
    }

    /**
     * The pattern is ANCHORED at both ends, which `fnmatch()` is and a regex
     * is not unless you say so.
     */
    public function testTheTranslationIsAnchoredAtBothEnds(): void
    {
        self::assertFalse(SkillRegistry::pathMatches('src/a.php', 'x/src/a.php'));
        self::assertFalse(SkillRegistry::pathMatches('src/a.php', 'src/a.phpx'));
        // /D, so a trailing newline cannot satisfy `$`.
        self::assertFalse(SkillRegistry::pathMatches('src/a.php', "src/a.php\n"));
    }

    /**
     * A pattern the translation cannot compile is answered by the FULL old
     * predicate — the three rewrites included — not by a bare `fnmatch()`, and
     * not by `false`.
     *
     * The case is not hypothetical and not malformed input. `fnmatch()`
     * inherits POSIX character classes from libc, so `[[:alpha:]]` is a
     * supported `paths:` shape; the translation emits `#^[[:alpha:]\]x$#D`,
     * whose class never terminates, and PCRE refuses it. Answering false there
     * would narrow the matcher for every skill that uses one.
     *
     * MEASURED on PHP 8.3.6, and this is the discriminating pair: for
     * `src/**\/[[:alpha:]]*.php` against `src/abc.php`, bare `fnmatch()` is
     * FALSE and the old predicate is TRUE — the zero-directory rewrite is what
     * carries it. A fallback that dropped the rewrites would still be green on
     * every other assertion in this file.
     */
    public function testAPosixClassPatternFallsBackToTheFullOldPredicate(): void
    {
        // The premise: PCRE really does refuse what the translation emits.
        self::assertFalse(@preg_match('#^[[:alpha:]\]x$#D', 'ax'));
        // ...and fnmatch really does honour the class.
        self::assertTrue(fnmatch('[[:alpha:]]x', 'ax'));

        self::assertTrue(SkillRegistry::pathMatches('[[:alpha:]]x', 'ax'));
        self::assertFalse(SkillRegistry::pathMatches('[[:alpha:]]x', '1x'));

        // The discriminator. Bare fnmatch says false here; the rewrites say true.
        self::assertFalse(fnmatch('src/**/[[:alpha:]]*.php', 'src/abc.php'));
        self::assertTrue(SkillRegistry::pathMatches('src/**/[[:alpha:]]*.php', 'src/abc.php'));
        self::assertTrue(SkillRegistry::pathMatches('src/**/[[:alpha:]]*.php', 'src/x/abc.php'));
        self::assertFalse(SkillRegistry::pathMatches('src/**/[[:alpha:]]*.php', 'src/123.php'));
    }

    /**
     * A class that is malformed rather than merely untranslated still answers
     * rather than throwing.
     *
     * `[z-a]` is a reversed range: PCRE refuses it and `fnmatch()` answers
     * false, so the value is uninteresting — what is being pinned is that a
     * tool call touching a file does not blow up on someone else's frontmatter.
     */
    public function testAMalformedClassAnswersInsteadOfThrowing(): void
    {
        self::assertFalse(SkillRegistry::pathMatches('a[z-a]b', 'azb'));
        self::assertFalse(SkillRegistry::pathMatches('a[z-a]b', 'a[z-a]b'));
    }

    /**
     * And the fix is reachable through the production entry point, not only
     * through the static helper the table exercises.
     */
    public function testGetForPathsClaimsARootFileForALeadingGlobstarSkill(): void
    {
        $registry = new SkillRegistry();
        $registry->register(['php' => $this->skill('php', ['**/*.php'])]);

        self::assertSame(
            ['php'],
            array_map(static fn (Skill $s): string => $s->name, $registry->getForPaths(['a.php'])),
        );
        self::assertSame(
            [],
            array_map(static fn (Skill $s): string => $s->name, $registry->getForPaths(['a.md'])),
        );
    }

    /**
     * @param list<string> $paths
     */
    private function skill(string $name, array $paths): Skill
    {
        return new Skill(
            name: $name,
            description: 'd',
            userInvocable: true,
            disableModelInvocation: false,
            allowedTools: null,
            disallowedTools: null,
            model: null,
            effort: 'medium',
            context: 'shared',
            paths: $paths,
            content: '',
            sourcePath: '/tmp/' . $name . '/SKILL.md',
        );
    }
}
