<?php

declare(strict_types=1);

namespace SugarCraft\Crush\Tests\Media;

use InvalidArgumentException;
use PHPUnit\Framework\TestCase;
use SugarCraft\Crush\Media\Infotext;
use SugarCraft\Crush\Media\MediaRequest;
use SugarCraft\Crush\Media\Png;

/**
 * Plan W1.7 gates for the PNG infotext container codec: golden byte pins
 * computed EXTERNALLY (python zlib.crc32 over chunk type+data — the
 * CRC-with-type trap of the review brief reddens a no-type implementation),
 * the frozen `tiny-parameters.png` fixture (4x4, two text chunks so the
 * `existing_pnginfo` preservation law is pinned: a parameters rewrite must
 * not drop the unrelated `Software` tEXt), in-place replace-never-append,
 * tEXt-vs-iTXt keyword priority (iTXt wins, PNG spec §4.2.3.1), latin-1 vs
 * UTF-8 strategy (ASCII → tEXt; CJK → compressed iTXt, re-read equal),
 * truncated/CRC-tampered damage → reader null / writer throws, the 64 MiB
 * boundary on input AND output, and the gd encode path (ext-gd present on
 * this box — the encodeGd tests run ungated).
 */
final class PngTest extends TestCase
{
    /** Frozen fixture bytes, generated by hand-chunk-building at W1.7 probe time. */
    private const FIXTURE = __DIR__ . '/../fixtures/png/tiny-parameters.png';

    private const FIXTURE_MD5 = '1043309f5571958a469e7ae7a4fa9a71';

    private const FIXTURE_PARAMS = "a cat, sitting\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 42, Size: 4x4, Version: v1.10.1";

    /** Golden chunk frames (python zlib.crc32 over type+data) — external oracles. */
    private const GOLD_SOFTWARE_CHUNK = '0000001f74455874536f66747761726500737461626c652d646966667573696f6e2d7765627569d3d33661';

    private const GOLD_PARAMS_CHUNK = '0000006a74455874706172616d65746572730061206361742c2073697474696e670a53746570733a2032302c2053616d706c65723a2045756c657220612c20434647207363616c653a20372c20536565643a2034322c2053697a653a203478342c2056657273696f6e3a2076312e31302e3158d0a0cd';

    private const GOLD_REPLACEMENT_CHUNK = '0000000c74455874706172616d65746572730058dd0bbcd0';

    private const GOLD_CJK_ITXT_CHUNK = '0000004069545874706172616d6574657273000100000078da012600d9ffe78cabe38081e38199e3828fe381a3e381a6e38184e3828b20e2809420c3bc6ec3af636f6465deef170d74f6967d';

    private const CJK_TEXT = '猫、すわっている — ünïcode';

    public function testIsPngSniffsTheEightByteSignature(): void
    {
        self::assertTrue(Png::isPng(self::bytes()));
        self::assertTrue(Png::isPng("\x89PNG\r\n\x1a\n" . 'anything at all'));
        self::assertFalse(Png::isPng('GIF89a' . str_repeat("\x00", 10)));
        self::assertFalse(Png::isPng("\x89PN"));
        self::assertFalse(Png::isPng(''));
    }

    public function testFixtureBytesAreTheFrozenReviewedImage(): void
    {
        $bytes = self::bytes();
        self::assertSame(267, strlen($bytes));
        self::assertSame(self::FIXTURE_MD5, md5($bytes));
        // The parameters chunk inside the fixture equals the externally computed golden frame.
        self::assertStringContainsString(hex2bin(self::GOLD_PARAMS_CHUNK), $bytes);
        self::assertStringContainsString(hex2bin(self::GOLD_SOFTWARE_CHUNK), $bytes);
    }

    public function testReadTextExtractsParametersFromTheFixture(): void
    {
        self::assertSame(self::FIXTURE_PARAMS, Png::readText(self::bytes()));
        self::assertSame('stable-diffusion-webui', Png::readText(self::bytes(), 'Software'));
    }

    public function testReadTextReturnsNullForAbsentKeyword(): void
    {
        self::assertNull(Png::readText(self::bytes(), 'no-such-keyword'));
    }

    public function testReaderRefusesDamageWithoutThrowing(): void
    {
        $bytes = self::bytes();
        // Truncated tail (mid-chunk).
        self::assertNull(Png::readText(substr($bytes, 0, strlen($bytes) - 4)));
        self::assertNull(Png::readText(substr($bytes, 0, 20)));
        // CRC tamper: flip ONE DATA byte of the parameters chunk, keep the stale CRC.
        $needle = hex2bin(self::GOLD_PARAMS_CHUNK);
        $dataPos = strpos($bytes, $needle) + 8 + 2; // signature-skipped chunk start + len/type already consumed → into payload
        $tampered = $bytes;
        $tampered[$dataPos] = $tampered[$dataPos] === 'b' ? 'c' : 'b';
        self::assertNotSame($bytes, $tampered);
        self::assertNull(Png::readText($tampered));
        // Non-PNG and empty.
        self::assertNull(Png::readText('not a png at all, really'));
        self::assertNull(Png::readText(''));
    }

    public function testWriteTextReplacesTheParametersChunkInPlace(): void
    {
        $strategy = null;
        $out = Png::writeText(self::bytes(), 'parameters', 'X', $strategy);
        self::assertSame(Png::STRATEGY_TEXT, $strategy);
        self::assertSame('X', Png::readText($out));
        // Golden byte pin: exactly the fixture with the external golden replacement chunk spliced in.
        $head = substr(self::bytes(), 0, strpos(self::bytes(), hex2bin(self::GOLD_PARAMS_CHUNK)));
        $tail = substr(self::bytes(), strlen($head) + strlen(hex2bin(self::GOLD_PARAMS_CHUNK)));
        self::assertSame($head . hex2bin(self::GOLD_REPLACEMENT_CHUNK) . $tail, $out);
    }

    public function testWriteTextPreservesForeignChunksIncludingOrdering(): void
    {
        $png = self::withExtras();
        $out = Png::writeText($png, 'parameters', 'fresh');
        $types = self::chunkTypes($out);
        // Same sequence as fed in: extras were appended after the fixture's text chunks.
        self::assertSame(['IHDR', 'IDAT', 'tEXt', 'tEXt', 'sRGB', 'eXIf', 'IEND'], $types);
        self::assertSame('fresh', Png::readText($out, 'parameters'));
        self::assertSame('stable-diffusion-webui', Png::readText($out, 'Software'));
        // The ancillary non-text chunks survive byte-identically (re-emit from original slices).
        foreach (['sRGB', 'eXIf'] as $type) {
            self::assertStringContainsString(self::chunkOf($png, $type), $out);
        }
    }

    public function testDoubleWriteReplacesNeverAppends(): void
    {
        $once = Png::writeText(self::bytes(), 'parameters', 'first');
        $twice = Png::writeText($once, 'parameters', 'second');
        self::assertSame(1, substr_count($twice, 'parameters'));
        self::assertSame('second', Png::readText($twice));
        // Writing the very same text again is byte-stable.
        self::assertSame($twice, Png::writeText($twice, 'parameters', 'second'));
    }

    public function testWriteTextInsertsBeforeIendWhenKeywordAbsent(): void
    {
        $out = Png::writeText(self::bytes(), 'Author', 'hush');
        $types = self::chunkTypes($out);
        self::assertSame('IEND', $types[count($types) - 1]);
        self::assertSame('tEXt', $types[count($types) - 2]);
        self::assertSame('hush', Png::readText($out, 'Author'));
        // Round-trip read→write→read keeps the original chunk readable.
        self::assertSame(self::FIXTURE_PARAMS, Png::readText($out));
    }

    public function testNonAsciiTextTakesTheCompressedITxtStrategyAndRoundTrips(): void
    {
        $strategy = null;
        $out = Png::writeText(self::bytes(), 'parameters', self::CJK_TEXT, $strategy);
        self::assertSame(Png::STRATEGY_ITXT, $strategy);
        self::assertSame(self::CJK_TEXT, Png::readText($out));
        self::assertStringContainsString(hex2bin(self::GOLD_CJK_ITXT_CHUNK), $out);
    }

    public function testLatinOnePayloadRidesRawTextAndReadsBackByteIdentical(): void
    {
        $latin1 = "caf\xe9 generator"; // raw latin-1 byte, not valid UTF-8 → A1111's raw-str tEXt arm
        $strategy = null;
        $out = Png::writeText(self::bytes(), 'legacy', $latin1, $strategy);
        self::assertSame(Png::STRATEGY_TEXT, $strategy);
        self::assertSame($latin1, Png::readText($out, 'legacy'));
    }

    public function testITxtBeatsTextForTheSameKeyword(): void
    {
        // Build both chunk types carrying one keyword by hand: a tEXt first, an iTXt after.
        $png = self::withTextChunks(self::bytes(), [
            self::chunkBytes('tEXt', "dup\x00from-text"),
            self::chunkBytes('iTXt', "dup\x00" . chr(0) . chr(0) . "\x00\x00from-itxt"),
        ]);
        self::assertSame('from-itxt', Png::readText($png, 'dup'));
        // And the tEXt arm is still readable when no iTXt shares the keyword.
        $textOnly = self::withTextChunks(self::bytes(), [self::chunkBytes('tEXt', "solo\x00just-text")]);
        self::assertSame('just-text', Png::readText($textOnly, 'solo'));
    }

    public function testCompressedITxtIsInflatedByTheReader(): void
    {
        $png = self::withTextChunks(self::bytes(), [hex2bin(self::GOLD_CJK_ITXT_CHUNK)]);
        self::assertSame(self::CJK_TEXT, Png::readText($png));
    }

    public function testWriterRefusesBadInputsLoudly(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('not a PNG');
        Png::writeText('definitely not a png', 'parameters', 'x');
    }

    public function testWriterRefusesTamperedCrc(): void
    {
        $bytes = self::bytes();
        $pos = strpos($bytes, hex2bin(self::GOLD_SOFTWARE_CHUNK)) + 9; // first payload byte of Software chunk
        $bytes[$pos] = 'S';
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('framing damaged');
        Png::writeText($bytes, 'parameters', 'x');
    }

    public function testWriterRefusesIllegalKeywords(): void
    {
        foreach (['', str_repeat('k', 80), "nul\x00here", ' pad '] as $keyword) {
            try {
                Png::writeText(self::bytes(), $keyword, 'x');
                self::fail('keyword ' . json_encode($keyword) . ' should have been refused');
            } catch (InvalidArgumentException $e) {
                self::assertStringContainsString('keyword', $e->getMessage());
            }
        }
    }

    public function testWriterRefusesNulInText(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('NUL');
        Png::writeText(self::bytes(), 'parameters', "evil\x00payload");
    }

    public function testSixtyFourMibBoundaryIsRefusedOnInputAndProducedOutput(): void
    {
        $big = "\x89PNG\r\n\x1a\n" . str_repeat("\x00", Png::MAX_BYTES);
        self::assertGreaterThan(Png::MAX_BYTES, strlen($big));
        self::assertNull(Png::readText($big));
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('64 MiB');
        Png::writeText($big, 'parameters', 'x');
    }

    public function testProducedOutputBeyondCeilingIsRefused(): void
    {
        // A PNG just under the cap plus a > cap payload: the rebuild must refuse to emit it.
        $base = self::bytes();
        $headroom = Png::MAX_BYTES - strlen($base) - 64;
        self::assertGreaterThan(0, $headroom);
        $text = str_repeat('x', $headroom + 1024);
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('exceed the 64 MiB ceiling');
        Png::writeText($base, 'parameters', $text);
    }

    public function testSetInfotextStampsParametersAndSyncsAnExistingPromptChunk(): void
    {
        $png = self::withTextChunks(self::bytes(), [
            self::chunkBytes('iTXt', "prompt\x00" . chr(0) . chr(0) . "\x00\x00a cat, sitting"),
        ]);
        $text = "a dog, running\nSteps: 30";
        $stamped = Png::setInfotext($png, $text);
        self::assertSame($text, Png::readText($stamped));
        self::assertSame('a dog, running', Png::readText($stamped, 'prompt'));
        self::assertSame(1, self::keywordOccurrences($stamped, 'prompt'));
        // A file WITHOUT a prompt chunk is not given one (minimal-diff law).
        $plain = Png::setInfotext(self::bytes(), $text);
        self::assertNull(Png::readText($plain, 'prompt'));
    }

    public function testEndToEndWithInfotextCodec(): void
    {
        // The W1.6→W1.7 seam: emit → embed → read == Infotext round-trip.
        $request = MediaRequest::new()
            ->withPrompt('a cat, sitting')
            ->withNegativePrompt('blurry')
            ->withSteps(20);
        $emitted = Infotext::emit($request);
        $stamped = Png::setInfotext(self::bytes(), $emitted);
        $back = Png::readText($stamped);
        self::assertSame($emitted, $back);
        $parsed = Infotext::parse((string) $back);
        self::assertSame('a cat, sitting', $parsed[Infotext::PROMPT_KEY]);
        self::assertSame('20', $parsed['Steps']);
    }

    public function testEncodeGdProducesReadablePngStampableWithInfotext(): void
    {
        $image = imagecreatetruecolor(2, 2);
        imagefill($image, 0, 0, imagecolorallocate($image, 10, 20, 30));
        $bytes = Png::encodeGd($image);
        imagedestroy($image);
        self::assertTrue(Png::isPng($bytes));
        $header = unpack('Nwidth/Nheight/Cdepth/Ccolor/Ccompress/Cfilter/Cinterlace', substr($bytes, 16, 13));
        self::assertSame(2, $header['width']);
        self::assertSame(2, $header['height']);
        $stamped = Png::setInfotext($bytes, self::CJK_TEXT);
        self::assertSame(self::CJK_TEXT, Png::readText($stamped));
        // Still a valid image after stamping.
        $reopened = imagecreatefromstring($stamped);
        self::assertNotFalse($reopened);
        imagedestroy($reopened);
    }

    public function testStrategyForSplitsAsciiUtfEightFromRawEightBit(): void
    {
        self::assertSame(Png::STRATEGY_TEXT, Png::strategyFor('plain ascii'));
        self::assertSame(Png::STRATEGY_ITXT, Png::strategyFor(self::CJK_TEXT));
        // Raw latin-1 (not valid UTF-8) keeps A1111's raw-str tEXt arm.
        self::assertSame(Png::STRATEGY_TEXT, Png::strategyFor("caf\xe9"));
    }

    // ------------------------------------------------------------------ helpers

    private static function bytes(): string
    {
        $bytes = file_get_contents(self::FIXTURE);
        self::assertIsString($bytes);

        return $bytes;
    }

    /** @return list<string> chunk type names in file order */
    private static function chunkTypes(string $png): array
    {
        $types = [];
        $offset = 8;
        while ($offset + 8 <= strlen($png)) {
            $length = unpack('N', substr($png, $offset, 4))[1];
            $types[] = substr($png, $offset + 4, 4);
            $offset += 12 + $length;
        }

        return $types;
    }

    private static function chunkOf(string $png, string $type): string
    {
        $offset = 8;
        while ($offset + 8 <= strlen($png)) {
            $length = unpack('N', substr($png, $offset, 4))[1];
            if (substr($png, $offset + 4, 4) === $type) {
                return substr($png, $offset, 12 + $length);
            }
            $offset += 12 + $length;
        }
        self::fail("no {$type} chunk");
    }

    /** Append raw chunk frames after the fixture's IDAT, before its IEND. */
    private static function withTextChunks(string $png, array $frames): string
    {
        $iend = substr($png, -12);
        self::assertSame('IEND', substr($iend, 4, 4));

        return substr($png, 0, -12) . implode('', $frames) . $iend;
    }

    /** A fixture carrying the ancillary chunks the preservation law must keep. */
    private static function withExtras(): string
    {
        return self::withTextChunks(self::bytes(), [
            self::chunkBytes('sRGB', "\x00"),
            self::chunkBytes('eXIf', "Exif\x00\x00mm"),
        ]);
    }

    private static function chunkBytes(string $type, string $data): string
    {
        return pack('N', strlen($data)) . $type . $data . pack('N', crc32($type . $data));
    }

    private static function keywordOccurrences(string $png, string $keyword): int
    {
        return substr_count($png, $keyword . "\x00");
    }
}
