<?php

declare(strict_types=1);

namespace SugarCraft\Crush\Protocol\Schema;

use SugarCraft\Crush\Protocol\Dispatcher;
use SugarCraft\Crush\Protocol\EventType;
use SugarCraft\Crush\Protocol\MethodRegistry;
use SugarCraft\Crush\Protocol\MethodSpec;

/**
 * The `sugarcrush.v1` schema document (roadmap O-3c, Appendix O §6.11):
 * `docs/protocol/sugarcrush.v1.schema.json`, and the method and event tables
 * of `docs/SERVER.md`, both generated from the code that serves the protocol —
 * the {@see MethodRegistry} (names, scopes, descriptions), {@see MethodSchemas}
 * (params, results), {@see EventType} and {@see EventSchemas} (the catalogue
 * and its data) and {@see Definitions} (the shared shapes).
 *
 * `scripts/gen-protocol-schema.php --write` rewrites both; `--check` (and
 * `ProtocolSchemaDriftTest`) fails when either has drifted. A web client
 * generates its types from the JSON document, so a method or field that is
 * not in the code is never in the client either.
 */
final class ProtocolSchema
{
    /** The schema file, relative to sugar-crush/. */
    public const SCHEMA_FILE = 'docs/protocol/sugarcrush.v1.schema.json';

    /** The page whose marked tables are generated, relative to sugar-crush/. */
    public const SERVER_DOC = 'docs/SERVER.md';

    public const METHODS_BEGIN = '<!-- protocol:methods:begin (generated by scripts/gen-protocol-schema.php — do not edit) -->';
    public const METHODS_END = '<!-- protocol:methods:end -->';
    public const EVENTS_BEGIN = '<!-- protocol:events:begin (generated by scripts/gen-protocol-schema.php — do not edit) -->';
    public const EVENTS_END = '<!-- protocol:events:end -->';

    private const IDEMPOTENCY_KEY = 'idempotencyKey';

    private static ?SchemaValidator $validator = null;

    private function __construct(private readonly MethodRegistry $methods)
    {
    }

    /** The schema of $methods, or of the full v1 roster. */
    public static function new(?MethodRegistry $methods = null): self
    {
        return new self($methods ?? Dispatcher::methods());
    }

    /**
     * Every way $params breaks $method's params schema; empty when they fit,
     * or when $method has no schema.
     *
     * @param array<string, mixed> $params
     * @return list<string>
     */
    public static function paramErrors(string $method, array $params): array
    {
        $schema = MethodSchemas::params($method);
        if ($schema === null) {
            return [];
        }

        return self::validator()->errors($params, $schema->toArray(), 'params');
    }

    /**
     * Every way $value breaks $schema, references resolved against the
     * shared definitions.
     *
     * @return list<string>
     */
    public static function errors(mixed $value, Schema $schema, string $path = '$'): array
    {
        return self::validator()->errors($value, $schema->toArray(), $path);
    }

    /**
     * The whole document.
     *
     * @return array<string, mixed>
     */
    public function document(): array
    {
        $methods = [];
        foreach ($this->methods->all() as $spec) {
            [$params, $result] = MethodSchemas::all()[$spec->name] ?? [Schema::object(), Schema::any()];
            if ($spec->sideEffects) {
                $params = $params->with([self::IDEMPOTENCY_KEY => Schema::string(64)->describe('A retry with the same key gets the original answer (5 min).')]);
            }
            $methods[$spec->name] = [
                'description' => $spec->description,
                'scope' => $spec->scope->value,
                'idempotent' => $spec->sideEffects,
                'params' => $params->toArray(),
                'result' => $result->toArray(),
            ];
        }

        $events = [];
        foreach (EventType::all() as $type) {
            $events[$type] = [
                'description' => EventType::description($type),
                'durable' => EventType::isDurable($type),
                'scope' => EventType::scope($type),
                'data' => (EventSchemas::data($type) ?? Schema::object())->toArray(),
            ];
        }

        return [
            '$schema' => 'https://json-schema.org/draft/2020-12/schema',
            '$id' => 'urn:sugarcraft:sugarcrush:protocol:v1',
            'title' => 'sugarcrush.v1',
            'description' => 'The sugar-crush server protocol: JSON-RPC 2.0 over the `sugarcrush.v1` WebSocket subprotocol. '
                . '`methods` holds each request\'s params and result; `events` holds the data of each `event` notification, '
                . 'whose params are `$defs/EventEnvelope`. Generated by scripts/gen-protocol-schema.php from src/Protocol — do not edit.',
            'protocol' => Dispatcher::PROTOCOL,
            '$defs' => \array_map(static fn (Schema $schema): array => $schema->toArray(), Definitions::all()),
            'methods' => $methods,
            'events' => $events,
        ];
    }

    /** The document as the schema file holds it. */
    public function json(): string
    {
        return (string) \json_encode(
            self::objects($this->document()),
            \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES | \JSON_UNESCAPED_UNICODE | \JSON_PRESERVE_ZERO_FRACTION | \JSON_THROW_ON_ERROR,
        ) . "\n";
    }

    /** The `docs/SERVER.md` method table. */
    public function methodsTable(): string
    {
        $lines = ['| Method | Scope | Idempotent | Required params | What it does |', '|---|---|---|---|---|'];
        foreach ($this->methods->all() as $spec) {
            $lines[] = \sprintf(
                '| `%s` | %s | %s | %s | %s |',
                $spec->name,
                $spec->scope->value,
                $spec->sideEffects ? 'yes' : '',
                self::requiredParams($spec),
                \str_replace('|', '\\|', $spec->description),
            );
        }

        return \implode("\n", $lines);
    }

    /** The `docs/SERVER.md` event table. */
    public function eventsTable(): string
    {
        $lines = ['| Type | Scope | Kind | What it says |', '|---|---|---|---|'];
        foreach (EventType::all() as $type) {
            $lines[] = \sprintf(
                '| `%s` | %s | %s | %s |',
                $type,
                EventType::scope($type),
                EventType::isDurable($type) ? 'durable' : 'live',
                \str_replace('|', '\\|', EventType::description($type)),
            );
        }

        return \implode("\n", $lines);
    }

    /**
     * $page (docs/SERVER.md) with its two marked tables regenerated.
     *
     * @throws \RuntimeException when a marker pair is missing
     */
    public function renderServerDoc(string $page): string
    {
        $page = self::replaceBlock($page, self::METHODS_BEGIN, self::METHODS_END, $this->methodsTable());

        return self::replaceBlock($page, self::EVENTS_BEGIN, self::EVENTS_END, $this->eventsTable());
    }

    private static function replaceBlock(string $page, string $begin, string $end, string $body): string
    {
        $from = \strpos($page, $begin);
        $to = \strpos($page, $end);
        if ($from === false || $to === false || $to < $from) {
            throw new \RuntimeException(\sprintf('%s has no %s … %s block', self::SERVER_DOC, $begin, $end));
        }

        return \substr($page, 0, $from) . $begin . "\n" . $body . "\n" . \substr($page, $to);
    }

    private static function requiredParams(MethodSpec $spec): string
    {
        $schema = MethodSchemas::params($spec->name)?->toArray() ?? [];
        $required = $schema['required'] ?? [];

        return $required === [] ? '—' : \implode(', ', \array_map(static fn (string $name): string => '`' . $name . '`', $required));
    }

    private static function validator(): SchemaValidator
    {
        return self::$validator ??= SchemaValidator::new(\array_map(static fn (Schema $schema): array => $schema->toArray(), Definitions::all()));
    }

    /**
     * Empty arrays become `{}`: in a schema document an empty node is "any
     * value", and `[]` would be read as a malformed schema.
     */
    private static function objects(mixed $value): mixed
    {
        if (!\is_array($value)) {
            return $value;
        }
        if ($value === []) {
            return new \stdClass();
        }

        return \array_map(self::objects(...), $value);
    }
}
